/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author VICTUS
 */
public class Menu extends javax.swing.JFrame {
    private JFileChooser fc;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }
    
    public File getFile() {
        fc = new JFileChooser(System.getProperty("user.dir"));
        fc.showOpenDialog(fc);
        return fc.getSelectedFile();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Bttoningresar = new javax.swing.JButton();
        Bttonconsulta = new javax.swing.JButton();
        Bttonsalir = new javax.swing.JButton();
        btnArchivo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/Menu/Dialogo T.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 380, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/Menu/Titulo Scoville APP.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 1190, 360));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/Menu/Buttehead.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, -60, -1, -1));

        Bttoningresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/Menu/Boton Ingresar.png"))); // NOI18N
        Bttoningresar.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 14, 14, 5, new java.awt.Color(0, 0, 0)));
        jPanel1.add(Bttoningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 320, 140));

        Bttonconsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/Menu/Boton Consulta.png"))); // NOI18N
        Bttonconsulta.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 14, 14, 5, new java.awt.Color(0, 0, 0)));
        jPanel1.add(Bttonconsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 310, 140));

        Bttonsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/Menu/Boton Salir.png"))); // NOI18N
        Bttonsalir.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 14, 14, 5, new java.awt.Color(0, 0, 0)));
        jPanel1.add(Bttonsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 210, 80));

        btnArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/Menu/Boton Archivo.png"))); // NOI18N
        btnArchivo.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 14, 14, 5, new java.awt.Color(0, 0, 0)));
        jPanel1.add(btnArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 100, 80));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/Menu/Imagen Fuego.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-170, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bttonconsulta;
    public javax.swing.JButton Bttoningresar;
    public javax.swing.JButton Bttonsalir;
    public javax.swing.JButton btnArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
